<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.1" language="es">
<context>
    <name>CopyAdditionalFiles</name>
    <message>
        <location filename="../CxfreezeExecDialog.py" line="285"/>
        <source>No such file or directory: &apos;{0}&apos;</source>
        <translation>No existe este archivo o directorio: &apos;{0}&apos;</translation>
    </message>
    <message>
        <location filename="../CxfreezeExecDialog.py" line="301"/>
        <source>
Copying {0}: </source>
        <translation>
Copiando {0}: </translation>
    </message>
    <message>
        <location filename="../CxfreezeExecDialog.py" line="320"/>
        <source>ok</source>
        <translation>ok</translation>
    </message>
    <message>
        <location filename="../CxfreezeExecDialog.py" line="322"/>
        <source>failed: {0}</source>
        <translation>ha fallado: {0}</translation>
    </message>
</context>
<context>
    <name>CxFreezePlugin</name>
    <message>
        <location filename="../../PluginCxFreeze.py" line="58"/>
        <source>Packagers - cx_freeze</source>
        <translation>Empaquetadores - cx_freeze</translation>
    </message>
    <message>
        <location filename="../../PluginCxFreeze.py" line="341"/>
        <source>There is no main script defined for the current project.</source>
        <translation>No hay script principal definido para el proyecto actual.</translation>
    </message>
    <message>
        <location filename="../../PluginCxFreeze.py" line="354"/>
        <source>The cxfreeze executable could not be found.</source>
        <translation>No se ha podido encontrar el ejecutable de cxfreeze.</translation>
    </message>
    <message>
        <location filename="../../PluginCxFreeze.py" line="354"/>
        <source>cxfreeze</source>
        <translation>cxfreeze</translation>
    </message>
    <message>
        <location filename="../../PluginCxFreeze.py" line="266"/>
        <source>Use cx_freeze</source>
        <translation>Usar cx_freeze</translation>
    </message>
    <message>
        <location filename="../../PluginCxFreeze.py" line="266"/>
        <source>Use cx_&amp;freeze</source>
        <translation>Usar cx_&amp;freeze</translation>
    </message>
    <message>
        <location filename="../../PluginCxFreeze.py" line="270"/>
        <source>Generate a distribution package using cx_freeze</source>
        <translation>Generar un paquete de distribución utilizando cx_freeze</translation>
    </message>
    <message>
        <location filename="../../PluginCxFreeze.py" line="272"/>
        <source>&lt;b&gt;Use cx_freeze&lt;/b&gt;&lt;p&gt;Generate a distribution package using cx_freeze. The command is executed in the project path. All files and directories must be given absolute or relative to the project directory.&lt;/p&gt;</source>
        <translation>&lt;b&gt;Usar cx_freeze&lt;/b&gt;&lt;p&gt;Generar un paquete de distribución utilizando cx_freeze. El comando se ejecuta en la ruta del proyecto. Todos los archivos y directorios deben ser proporcionados de forma absoluta o relativa al directorio del proyecto.&lt;/p&gt;</translation>
    </message>
    <message>
        <location filename="../../PluginCxFreeze.py" line="210"/>
        <source>The cxfreeze.bat executable could not be found.Did you run the cxfreeze-postinstall script?</source>
        <translation>No se puede hallar el ejecutable por lotes de cxfreeze. ¿Se ha ejecutado el script ponstinstalación de cxfreeze?</translation>
    </message>
</context>
<context>
    <name>CxfreezeConfigDialog</name>
    <message>
        <location filename="../CxfreezeConfigDialog.ui" line="14"/>
        <source>Cxfreeze Configuration</source>
        <translation>Configuración de Cxfreeze</translation>
    </message>
    <message>
        <location filename="../CxfreezeConfigDialog.ui" line="17"/>
        <source>&lt;b&gt;Cxfreeze Configuration&lt;/b&gt;
&lt;p&gt;This dialog is used to configure the cxfreeze (FreezePython) process in order to create a distribution package for the project.&lt;/p&gt;
&lt;p&gt;All files and directories must be given absolute or relative to the project directory.&lt;/p&gt;</source>
        <translation>&lt;b&gt;Configuración de Cxfreeze&lt;/b&gt;
&lt;p&gt;Este diálogo se utiliza para configurar el proceso cxfreeze (FreezePython) para crear paquetes de distribución para el proyecto.&lt;/p&gt;
&lt;p&gt;Todos los archivos y directorios deben ser proporcionados de forma absoluta o relativa al directorio del proyecto.&lt;/p&gt;</translation>
    </message>
    <message>
        <location filename="../CxfreezeConfigDialog.ui" line="47"/>
        <source>&amp;General</source>
        <translation>&amp;General</translation>
    </message>
    <message>
        <location filename="../CxfreezeConfigDialog.ui" line="177"/>
        <source>Select to optimize generated bytecode</source>
        <translation>Seleccionar para optimizar el bytecode generado</translation>
    </message>
    <message>
        <location filename="../CxfreezeConfigDialog.ui" line="180"/>
        <source>Optimize bytecode</source>
        <translation>Optimizar bytecode</translation>
    </message>
    <message>
        <location filename="../CxfreezeConfigDialog.ui" line="204"/>
        <source>Don&apos;t optimize</source>
        <translation>No optimizar</translation>
    </message>
    <message>
        <location filename="../CxfreezeConfigDialog.ui" line="211"/>
        <source>Select to optimize the generated bytecode</source>
        <translation>Seleccionar para optimizar el bytecode generado</translation>
    </message>
    <message>
        <location filename="../CxfreezeConfigDialog.ui" line="214"/>
        <source>Optimize</source>
        <translation>Optimizar</translation>
    </message>
    <message>
        <location filename="../CxfreezeConfigDialog.ui" line="221"/>
        <source>Select to optimize the generated bytecode and remove doc strings</source>
        <translation>Seleccionar para optimizar el bytecode generado y eliminar cadenas de documentación</translation>
    </message>
    <message>
        <location filename="../CxfreezeConfigDialog.ui" line="224"/>
        <source>Optimize (with docstring removal)</source>
        <translation>Optimizar (con eliminación de cadenas de documentación)</translation>
    </message>
    <message>
        <location filename="../CxfreezeConfigDialog.ui" line="78"/>
        <source>Select to disable copying of dependent files to the target directory</source>
        <translation>Seleccionar para deshabilitar el copiado de archivos dependientes al directorio de destino</translation>
    </message>
    <message>
        <location filename="../CxfreezeConfigDialog.ui" line="81"/>
        <source>Do not copy dependant files</source>
        <translation>No copiar archivos dependientes</translation>
    </message>
    <message>
        <location filename="../CxfreezeConfigDialog.ui" line="170"/>
        <source>Target directory:</source>
        <translation>Directorio de destino:</translation>
    </message>
    <message>
        <location filename="../CxfreezeConfigDialog.ui" line="144"/>
        <source>Enter the name of the target directory</source>
        <translation>Introduzca el nombre del directorio de destino</translation>
    </message>
    <message>
        <location filename="../CxfreezeConfigDialog.ui" line="147"/>
        <source>&lt;p&gt;Enter the name of the directory in which to place the target file and any dependant files.&lt;/p&gt;</source>
        <translation>&lt;p&gt;Introduzca el nombre del directorio en el cual se ubicará el archivo de destino y todos los archivos dependientes.&lt;/p&gt;</translation>
    </message>
    <message>
        <location filename="../CxfreezeConfigDialog.ui" line="127"/>
        <source>Enter the name of the file to create</source>
        <translation>Introduzca el nombre del archivo a crear</translation>
    </message>
    <message>
        <location filename="../CxfreezeConfigDialog.ui" line="130"/>
        <source>&lt;p&gt;Enter the name of the file to create instead of the base name of the script and the extension of the base binary.&lt;/p&gt;</source>
        <translation>&lt;p&gt;Introduzca el nombre del archivo a crear en lugar del nombre base del script y la extensión del binario base.&lt;/p&gt;</translation>
    </message>
    <message>
        <location filename="../CxfreezeConfigDialog.ui" line="120"/>
        <source>Target name:</source>
        <translation>Nombre de destino:</translation>
    </message>
    <message>
        <location filename="../CxfreezeConfigDialog.ui" line="60"/>
        <source>Enter name of script which will be executed upon startup</source>
        <translation>Introduzca el nombre del script que se ejecutará al iniciar</translation>
    </message>
    <message>
        <location filename="../CxfreezeConfigDialog.ui" line="154"/>
        <source>Enter the name of a file on which to base the target file</source>
        <translation>Introduzca el nombre del archivo en el que basar el archivo de destino</translation>
    </message>
    <message>
        <location filename="../CxfreezeConfigDialog.ui" line="113"/>
        <source>Init script:</source>
        <translation>Script de inicio:</translation>
    </message>
    <message>
        <location filename="../CxfreezeConfigDialog.ui" line="137"/>
        <source>Base name:</source>
        <translation>Nombre base:</translation>
    </message>
    <message>
        <location filename="../CxfreezeConfigDialog.ui" line="262"/>
        <source>&amp;Advanced</source>
        <translation>&amp;Avanzado</translation>
    </message>
    <message>
        <location filename="../CxfreezeConfigDialog.ui" line="274"/>
        <source>Default path</source>
        <translation>Ruta por defecto</translation>
    </message>
    <message>
        <location filename="../CxfreezeConfigDialog.ui" line="281"/>
        <source>Enter directories to initialize sys.path</source>
        <translation>Introduzca los directorios para inicializar sys.path</translation>
    </message>
    <message>
        <location filename="../CxfreezeConfigDialog.ui" line="284"/>
        <source>&lt;p&gt;Enter a list of paths separated by the standard path separator, which will be used to initialize sys.path prior to running the module finder.&lt;/p&gt;</source>
        <translation>&lt;p&gt;Introduzca una lista de rutas separadas por el separador estándar de rutas. Esta ruta se utilizará para inicializar sys.path antes de ejecutar el buscador de módulos.&lt;/p&gt;</translation>
    </message>
    <message>
        <location filename="../CxfreezeConfigDialog.ui" line="291"/>
        <source>Enter directories to modify sys.path</source>
        <translation>Introduzca directorios para modificar sys.path</translation>
    </message>
    <message>
        <location filename="../CxfreezeConfigDialog.ui" line="294"/>
        <source>&lt;p&gt;Enter a list of paths separated by the standard path separator, which will be used to modify sys.path prior to running the module finder.&lt;/p&gt;</source>
        <translation>&lt;p&gt;Introduzca una lista de rutas separadas por el separador estándar de rutas. Esta ruta se utilizará para modificar sys.path antes de ejecutar el buscador de módulos.&lt;/p&gt;</translation>
    </message>
    <message>
        <location filename="../CxfreezeConfigDialog.ui" line="301"/>
        <source>Include path</source>
        <translation>Ruta de include</translation>
    </message>
    <message>
        <location filename="../CxfreezeConfigDialog.ui" line="308"/>
        <source>Replace paths:</source>
        <translation>Rutas de reemplazamiento:</translation>
    </message>
    <message>
        <location filename="../CxfreezeConfigDialog.ui" line="315"/>
        <source>Enter replacement directives</source>
        <translation>Introduzca directivas de reemplazamiento</translation>
    </message>
    <message>
        <location filename="../CxfreezeConfigDialog.ui" line="318"/>
        <source>&lt;p&gt;Enter replacement directives used to replace all the paths in modules found. Please see cx_Freeze docu for details.&lt;/p&gt;</source>
        <translation>&lt;p&gt;Introduzca las directivas de reemplazamiento utilizadas para sustituir todas las rutas en los módulos encontrados. Por favor vea la documentación de cx_Freeze para detalles.&lt;/p&gt;</translation>
    </message>
    <message>
        <location filename="../CxfreezeConfigDialog.ui" line="325"/>
        <source>Include modules:</source>
        <translation>Incluir módulos:</translation>
    </message>
    <message>
        <location filename="../CxfreezeConfigDialog.ui" line="332"/>
        <source>Enter a comma separated list of modules to include</source>
        <translation>Introduzca una lista de módulos a incluir separados por comas</translation>
    </message>
    <message>
        <location filename="../CxfreezeConfigDialog.ui" line="339"/>
        <source>Exclude modules:</source>
        <translation>Excluir módulos:</translation>
    </message>
    <message>
        <location filename="../CxfreezeConfigDialog.ui" line="346"/>
        <source>Enter a comma separated list of modules to exclude</source>
        <translation>Introduzca una lista de módulos a excluir separados por comas</translation>
    </message>
    <message>
        <location filename="../CxfreezeConfigDialog.ui" line="380"/>
        <source>Press to select the external list file via a file selection dialog</source>
        <translation>Pulse para seleccionar el archivo de lista externo a traves de un diálogo de selección de archivo</translation>
    </message>
    <message>
        <location filename="../CxfreezeConfigDialog.ui" line="353"/>
        <source>Enter the name of a file in which to place the list of included modules</source>
        <translation>Introduzca el nombre de un archivo en el que ubicar la lista de módulos incluidos</translation>
    </message>
    <message>
        <location filename="../CxfreezeConfigDialog.ui" line="360"/>
        <source>External list file:</source>
        <translation>Archivo de lista externo:</translation>
    </message>
    <message>
        <location filename="../CxfreezeConfigDialog.py" line="403"/>
        <source>Select target directory</source>
        <translation>Seleccionar directorio de destino</translation>
    </message>
    <message>
        <location filename="../CxfreezeConfigDialog.py" line="351"/>
        <source>Select external list file</source>
        <translation>Seleccionar archivo de lista externo</translation>
    </message>
    <message>
        <location filename="../CxfreezeConfigDialog.ui" line="53"/>
        <source>Application icon:</source>
        <translation>Icono de la aplicación:</translation>
    </message>
    <message>
        <location filename="../CxfreezeConfigDialog.ui" line="248"/>
        <source>Enter the name of the application icon.</source>
        <translation>Introduzca el nombre del icono de la aplicación.</translation>
    </message>
    <message>
        <location filename="../CxfreezeConfigDialog.ui" line="88"/>
        <source>Select to compress the byte code in zip files</source>
        <translation>Seleccionar para comprimir el byte code en archivos zip</translation>
    </message>
    <message>
        <location filename="../CxfreezeConfigDialog.ui" line="91"/>
        <source>Compress Byte Code</source>
        <translation>Comprimir Byte Code</translation>
    </message>
    <message>
        <location filename="../CxfreezeConfigDialog.ui" line="234"/>
        <source>Select the cx_freeze executable</source>
        <translation>Seleccionar el ejecutable de cx_freeze</translation>
    </message>
    <message>
        <location filename="../CxfreezeConfigDialog.ui" line="241"/>
        <source>cx_Freeze executable:</source>
        <translation>Ejecutable de cx_freeze:</translation>
    </message>
    <message>
        <location filename="../CxfreezeConfigDialog.py" line="371"/>
        <source>Icons</source>
        <translation>Iconos</translation>
    </message>
    <message>
        <location filename="../CxfreezeConfigDialog.py" line="372"/>
        <source>All files</source>
        <translation>Todos los archivos</translation>
    </message>
    <message>
        <location filename="../CxfreezeConfigDialog.py" line="383"/>
        <source>Select the application icon</source>
        <translation>Seleccinar el icono para la aplicación</translation>
    </message>
    <message>
        <location filename="../CxfreezeConfigDialog.ui" line="388"/>
        <source>Additional &amp;files</source>
        <translation>Archivos &amp;adicionales</translation>
    </message>
    <message>
        <location filename="../CxfreezeConfigDialog.ui" line="401"/>
        <source>List of files and directories which are copied into the distribution directory
See &apos;What&apos;s this&apos;</source>
        <translation>Lista de archivos y directorios que se copiarán al directorio de distribución.
Ver &apos;qué es esto&apos;</translation>
    </message>
    <message>
        <location filename="../CxfreezeConfigDialog.ui" line="405"/>
        <source>&lt;html&gt;&lt;head/&gt;&lt;body&gt;&lt;p&gt;&lt;span style=&quot; font-weight:600;&quot;&gt;Additional files list&lt;/span&gt;&lt;/p&gt;&lt;p&gt;Here you can add files and folders which will not frozen by cx_Freeze, but maybe relevant to your application. This could be, e.g., some UI files or a dirctory with your translation files.&lt;/p&gt;&lt;p&gt;Easily add them to the list and they get copied after the freeze.&lt;/p&gt;&lt;p&gt;Remarks: &lt;/p&gt;&lt;p&gt;- Every file or folder will be copied relativ to the destination folder even if it&apos;s outside the sourcetree.&lt;/p&gt;&lt;p&gt;- Files and folders don&apos;t have to be added to the Eric project first.&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</source>
        <translation>&lt;html&gt;&lt;head/&gt;&lt;body&gt;&lt;p&gt;&lt;span style=&quot; font-weight:600;&quot;&gt;Listado de archivos adicionales&lt;/span&gt;&lt;/p&gt;&lt;p&gt;Aquí se pueden añadir archivos y directorios que no se congelarán con cx_Freeze, pero que pueden ser relevantes para la aplicación. Pueden ser, por ejemplo, archivos de UI o un directorio con archivos de traducciones.&lt;/p&gt;&lt;p&gt;Se pueden añadir de manera fácil a esta lista y serán copiados despues de la &apos;congelación&apos; con cx_freeze.&lt;/p&gt;&lt;p&gt;Observaciones: &lt;/p&gt;&lt;p&gt;- Cada archivo o directorio se copiara de manera relativa al directorio destino incluso si está fuera del árbol de códigos fuente.&lt;/p&gt;&lt;p&gt;- No es necesario añadir previamente los archivos y directorios al proyecto Eric.&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</translation>
    </message>
    <message>
        <location filename="../CxfreezeConfigDialog.ui" line="420"/>
        <source>Press to delete the selected entry from the list</source>
        <translation>Pulsar para borrar la entrada seleccionada de la lista</translation>
    </message>
    <message>
        <location filename="../CxfreezeConfigDialog.ui" line="423"/>
        <source>Delete</source>
        <translation>Borrar</translation>
    </message>
    <message>
        <location filename="../CxfreezeConfigDialog.ui" line="433"/>
        <source>Press to add the entered file or directory to the list</source>
        <translation>Pulsar para añadir la fila o directorio introducidos a la lista</translation>
    </message>
    <message>
        <location filename="../CxfreezeConfigDialog.ui" line="436"/>
        <source>Add</source>
        <translation>Añadir</translation>
    </message>
    <message>
        <location filename="../CxfreezeConfigDialog.ui" line="443"/>
        <source>Enter a file or directory to be added.
Wildcards are allowed, e.g. *.ui</source>
        <translation>Introducir un archivo o directorio a añadir.
Se pueden utilizar carácteres comodín, por ejemplo. *.ui</translation>
    </message>
    <message>
        <location filename="../CxfreezeConfigDialog.py" line="559"/>
        <source>Select files and folders</source>
        <translation>Seleccinar archivos y directorios</translation>
    </message>
    <message>
        <location filename="../CxfreezeConfigDialog.ui" line="451"/>
        <source>Press to select a file or directory via a selection dialog</source>
        <translation>Pulsar para seleccionar un archivo o directorio vía un diálogo de selección</translation>
    </message>
    <message>
        <location filename="../CxfreezeConfigDialog.ui" line="394"/>
        <source>Add depending files or folders to copy into the distribution folder:</source>
        <translation>Añadir archivos o directorios dependientes para copiar dentro de la carpeta de distribución:</translation>
    </message>
    <message>
        <location filename="../CxfreezeConfigDialog.ui" line="201"/>
        <source>Select to not optimize the generated bytecode</source>
        <translation>Seleccionar para no optimizar el bytecode generado</translation>
    </message>
</context>
<context>
    <name>CxfreezeExecDialog</name>
    <message>
        <location filename="../CxfreezeExecDialog.ui" line="14"/>
        <source>Cxfreeze</source>
        <translation>Cxfreeze</translation>
    </message>
    <message>
        <location filename="../CxfreezeExecDialog.ui" line="41"/>
        <source>&lt;b&gt;Packager Execution&lt;/b&gt;
&lt;p&gt;This shows the output of the packager command.&lt;/p&gt;</source>
        <translation>&lt;b&gt;Ejecución del empaquetador&lt;/b&gt;
&lt;p&gt;Muestra la salida del comando del empaquetador.&lt;/p&gt;</translation>
    </message>
    <message>
        <location filename="../CxfreezeExecDialog.ui" line="70"/>
        <source>&lt;b&gt;Packager Execution&lt;/b&gt;
&lt;p&gt;This shows the errors of the packager command.&lt;/p&gt;</source>
        <translation>&lt;b&gt;Ejecución del empaquetador&lt;/b&gt;
&lt;p&gt;Muestra los errores del comando del empaquetador.&lt;/p&gt;</translation>
    </message>
    <message>
        <location filename="../CxfreezeExecDialog.py" line="89"/>
        <source>{0} - {1}</source>
        <translation>{0} - {1}</translation>
    </message>
    <message>
        <location filename="../CxfreezeExecDialog.py" line="98"/>
        <source>Process Generation Error</source>
        <translation>Error de Generación de Proceso</translation>
    </message>
    <message>
        <location filename="../CxfreezeExecDialog.py" line="98"/>
        <source>The process {0} could not be started. Ensure, that it is in the search path.</source>
        <translation>El proceso {0} no pudo ser ejecutado. Asegúrese de que esta en la ruta de búsqueda.</translation>
    </message>
    <message>
        <location filename="../CxfreezeExecDialog.py" line="152"/>
        <source>
{0} finished.
</source>
        <translation>{0} ha terminado.</translation>
    </message>
    <message>
        <location filename="../CxfreezeExecDialog.ui" line="29"/>
        <source>Messages</source>
        <translation>Mensajes</translation>
    </message>
    <message>
        <location filename="../CxfreezeExecDialog.ui" line="58"/>
        <source>Errors</source>
        <translation>Errores</translation>
    </message>
    <message>
        <location filename="../CxfreezeExecDialog.py" line="138"/>
        <source>
{0} aborted.
</source>
        <translation>
{0} abortado.
</translation>
    </message>
</context>
</TS>
