<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS><TS version="2.0" language="de" sourcelanguage="">
<context>
    <name>CxFreezePlugin</name>
    <message>
        <location filename="../../PluginCxFreeze.py" line="59"/>
        <source>Packagers - cx_freeze</source>
        <translation>Paketierer - cx_freeze</translation>
    </message>
    <message>
        <location filename="../../PluginCxFreeze.py" line="327"/>
        <source>There is no main script defined for the current project.</source>
        <translation>Für das Projekt ist kein Hauptskript festgelegt.</translation>
    </message>
    <message>
        <location filename="../../PluginCxFreeze.py" line="337"/>
        <source>The cxfreeze executable could not be found.</source>
        <translation>Das cxfreeze Programm konnte nicht gefunden werden.</translation>
    </message>
    <message>
        <location filename="../../PluginCxFreeze.py" line="337"/>
        <source>cxfreeze</source>
        <translation>cxfreeze</translation>
    </message>
    <message>
        <location filename="../../PluginCxFreeze.py" line="255"/>
        <source>Use cx_freeze</source>
        <translation>Benutze cx_freeze</translation>
    </message>
    <message>
        <location filename="../../PluginCxFreeze.py" line="255"/>
        <source>Use cx_&amp;freeze</source>
        <translation>Benutze cx_&amp;freeze</translation>
    </message>
    <message>
        <location filename="../../PluginCxFreeze.py" line="258"/>
        <source>Generate a distribution package using cx_freeze</source>
        <translation>Erzeuge ein Distributionspaket mittels cx_freeze</translation>
    </message>
    <message>
        <location filename="../../PluginCxFreeze.py" line="260"/>
        <source>&lt;b&gt;Use cx_freeze&lt;/b&gt;&lt;p&gt;Generate a distribution package using cx_freeze. The command is executed in the project path. All files and directories must be given absolute or relative to the project directory.&lt;/p&gt;</source>
        <translation>&lt;b&gt;Benutze cx_freeze&lt;/b&gt;&lt;p&gt;Erzeuge ein Distributionspaket mittels cx_freeze. Der Befehl wird im Projektverzeichnis ausgeführt. Alle Datei- und Verzeichnisnamen müssen absolut oder relativ zum Projektverzeichnis angegeben werden.&lt;/p&gt;</translation>
    </message>
    <message>
        <location filename="../../PluginCxFreeze.py" line="24"/>
        <source>Your version of Eric5 is not supported. At least version 5.1.0 of Eric5 is needed.</source>
        <translation>Ihre verwendete Version von Eric5 wird nicht unterstützt. Mindestens Version 5.1.0 von Eric5 wird benötigt.</translation>
    </message>
</context>
<context>
    <name>CxfreezeConfigDialog</name>
    <message>
        <location filename="../../CxFreeze/CxfreezeConfigDialog.py" line="371"/>
        <source>Select target directory</source>
        <translation>Wähle das Zielverzeichnis</translation>
    </message>
    <message>
        <location filename="../../CxFreeze/CxfreezeConfigDialog.py" line="322"/>
        <source>Select external list file</source>
        <translation>Wähle die externe Listendatei</translation>
    </message>
    <message>
        <location filename="../../CxFreeze/CxfreezeConfigDialog.ui" line="14"/>
        <source>Cxfreeze Configuration</source>
        <translation>Cxfreeze Konfiguration</translation>
    </message>
    <message>
        <location filename="../../CxFreeze/CxfreezeConfigDialog.ui" line="17"/>
        <source>&lt;b&gt;Cxfreeze Configuration&lt;/b&gt;
&lt;p&gt;This dialog is used to configure the cxfreeze (FreezePython) process in order to create a distribution package for the project.&lt;/p&gt;
&lt;p&gt;All files and directories must be given absolute or relative to the project directory.&lt;/p&gt;</source>
        <translation>&lt;b&gt;Cxfreeze Konfiguration&lt;/b&gt;
&lt;p&gt;Dieser Dialog wird benutzt, um den cxfreeze (FreezePython) Prozess für die Herstellung eines Distributionspaketes zu konfigurieren.&lt;/p&gt;
&lt;p&gt;Alle Dateien und Verzeichnisse müssen absolut oder relativ zum Projektverzeichnis angegeben werden.&lt;/p&gt;</translation>
    </message>
    <message>
        <location filename="../../CxFreeze/CxfreezeConfigDialog.ui" line="47"/>
        <source>&amp;General</source>
        <translation>All&amp;gemein</translation>
    </message>
    <message>
        <location filename="../../CxFreeze/CxfreezeConfigDialog.ui" line="190"/>
        <source>Select to optimize generated bytecode</source>
        <translation>Auswählen, um den erzeugten Bytecode zu optimieren</translation>
    </message>
    <message>
        <location filename="../../CxFreeze/CxfreezeConfigDialog.ui" line="193"/>
        <source>Optimize bytecode</source>
        <translation>Bytecode optimieren</translation>
    </message>
    <message>
        <location filename="../../CxFreeze/CxfreezeConfigDialog.ui" line="214"/>
        <source>Don&apos;t optimize</source>
        <translation>Nicht optimieren</translation>
    </message>
    <message>
        <location filename="../../CxFreeze/CxfreezeConfigDialog.ui" line="221"/>
        <source>Select to optimize the generated bytecode</source>
        <translation>Auswählen, um den erzeugten Bytecode zu optimieren</translation>
    </message>
    <message>
        <location filename="../../CxFreeze/CxfreezeConfigDialog.ui" line="224"/>
        <source>Optimize</source>
        <translation>Optimieren</translation>
    </message>
    <message>
        <location filename="../../CxFreeze/CxfreezeConfigDialog.ui" line="231"/>
        <source>Select to optimize the generated bytecode and remove doc strings</source>
        <translation>Auswählen, um den erzeugten Bytecode zu optimieren und Docstrings zu entfernen</translation>
    </message>
    <message>
        <location filename="../../CxFreeze/CxfreezeConfigDialog.ui" line="234"/>
        <source>Optimize (with docstring removal)</source>
        <translation>Optimieren (Docstrings entfernen)</translation>
    </message>
    <message>
        <location filename="../../CxFreeze/CxfreezeConfigDialog.ui" line="81"/>
        <source>Select to disable copying of dependent files to the target directory</source>
        <translation>Auswählen, um das Kopieren der abhängigen Dateien in das Zielverzeichnis abzuschalten</translation>
    </message>
    <message>
        <location filename="../../CxFreeze/CxfreezeConfigDialog.ui" line="84"/>
        <source>Do not copy dependant files</source>
        <translation>Abhängige Dateien nicht kopieren</translation>
    </message>
    <message>
        <location filename="../../CxFreeze/CxfreezeConfigDialog.ui" line="183"/>
        <source>Target directory:</source>
        <translation>Zielverzeichnis:</translation>
    </message>
    <message>
        <location filename="../../CxFreeze/CxfreezeConfigDialog.ui" line="154"/>
        <source>Enter the name of the target directory</source>
        <translation>Gib den Namen des Zielverzeichnisses ein</translation>
    </message>
    <message>
        <location filename="../../CxFreeze/CxfreezeConfigDialog.ui" line="157"/>
        <source>&lt;p&gt;Enter the name of the directory in which to place the target file and any dependant files.&lt;/p&gt;</source>
        <translation>&lt;p&gt;Gib den Namen des Verzeichnisses an, in das die Zieldatei und alle abhängigen Dateien kopiert werden.&lt;/p&gt;</translation>
    </message>
    <message>
        <location filename="../../CxFreeze/CxfreezeConfigDialog.ui" line="130"/>
        <source>Enter the name of the file to create</source>
        <translation>Gib den Namen der zu erzeugenden Datei an</translation>
    </message>
    <message>
        <location filename="../../CxFreeze/CxfreezeConfigDialog.ui" line="133"/>
        <source>&lt;p&gt;Enter the name of the file to create instead of the base name of the script and the extension of the base binary.&lt;/p&gt;</source>
        <translation>&lt;p&gt;Gib den Namen der zu erzeugenden Datei an. Dieser wird anstelle des Basisnamens des Skriptes und der Erweiterung des Basisexecutables verwendet.&lt;/p&gt;</translation>
    </message>
    <message>
        <location filename="../../CxFreeze/CxfreezeConfigDialog.ui" line="123"/>
        <source>Target name:</source>
        <translation>Zielname:</translation>
    </message>
    <message>
        <location filename="../../CxFreeze/CxfreezeConfigDialog.ui" line="468"/>
        <source>...</source>
        <translation>...</translation>
    </message>
    <message>
        <location filename="../../CxFreeze/CxfreezeConfigDialog.ui" line="60"/>
        <source>Enter name of script which will be executed upon startup</source>
        <translation>Gib den Namen eines Skriptes an, das beim Start ausgeführt wird</translation>
    </message>
    <message>
        <location filename="../../CxFreeze/CxfreezeConfigDialog.ui" line="164"/>
        <source>Enter the name of a file on which to base the target file</source>
        <translation>Gib den Namen einer Datei an, auf der die Zieldatei basiert</translation>
    </message>
    <message>
        <location filename="../../CxFreeze/CxfreezeConfigDialog.ui" line="116"/>
        <source>Init script:</source>
        <translation>Init-Skript:</translation>
    </message>
    <message>
        <location filename="../../CxFreeze/CxfreezeConfigDialog.ui" line="140"/>
        <source>Base name:</source>
        <translation>Basisname:</translation>
    </message>
    <message>
        <location filename="../../CxFreeze/CxfreezeConfigDialog.ui" line="273"/>
        <source>&amp;Advanced</source>
        <translation>&amp;Spezielles</translation>
    </message>
    <message>
        <location filename="../../CxFreeze/CxfreezeConfigDialog.ui" line="285"/>
        <source>Default path</source>
        <translation>Standarpfad</translation>
    </message>
    <message>
        <location filename="../../CxFreeze/CxfreezeConfigDialog.ui" line="292"/>
        <source>Enter directories to initialize sys.path</source>
        <translation>Gib die Verzeichnisse zur Initialisierung von sys.path ein</translation>
    </message>
    <message>
        <location filename="../../CxFreeze/CxfreezeConfigDialog.ui" line="295"/>
        <source>&lt;p&gt;Enter a list of paths separated by the standard path separator, which will be used to initialize sys.path prior to running the module finder.&lt;/p&gt;</source>
        <translation>&lt;p&gt;Gib eine Liste von Verzeichnissen getrennt durch den standard Pfadtrenner ein. Diese werden verwendet, um sys.path vor der Ausführung des Modulfinders zu initialisieren.&lt;/p&gt;</translation>
    </message>
    <message>
        <location filename="../../CxFreeze/CxfreezeConfigDialog.ui" line="302"/>
        <source>Enter directories to modify sys.path</source>
        <translation>Gib die Verzeichnisse zur Modifizierung von sys.path ein</translation>
    </message>
    <message>
        <location filename="../../CxFreeze/CxfreezeConfigDialog.ui" line="305"/>
        <source>&lt;p&gt;Enter a list of paths separated by the standard path separator, which will be used to modify sys.path prior to running the module finder.&lt;/p&gt;</source>
        <translation>&lt;p&gt;Gib eine Liste von Verzeichnissen getrennt durch den standard Pfadtrenner ein. Diese werden verwendet, um sys.path vor der Ausführung des Modulfinders zu modifizieren.&lt;/p&gt;</translation>
    </message>
    <message>
        <location filename="../../CxFreeze/CxfreezeConfigDialog.ui" line="312"/>
        <source>Include path</source>
        <translation>Include Pfad</translation>
    </message>
    <message>
        <location filename="../../CxFreeze/CxfreezeConfigDialog.ui" line="319"/>
        <source>Replace paths:</source>
        <translation>Pfadersetzungen:</translation>
    </message>
    <message>
        <location filename="../../CxFreeze/CxfreezeConfigDialog.ui" line="326"/>
        <source>Enter replacement directives</source>
        <translation>Gib Ersetzungsregeln ein</translation>
    </message>
    <message>
        <location filename="../../CxFreeze/CxfreezeConfigDialog.ui" line="329"/>
        <source>&lt;p&gt;Enter replacement directives used to replace all the paths in modules found. Please see cx_Freeze docu for details.&lt;/p&gt;</source>
        <translation>&lt;p&gt;Gib Ersetzungsregeln ein, die benutzt werden, um Pfade in gefundenen Modulen zu ersetzen. Siehe die cx_Freeze Dokumentation für Details.&lt;/p&gt;</translation>
    </message>
    <message>
        <location filename="../../CxFreeze/CxfreezeConfigDialog.ui" line="336"/>
        <source>Include modules:</source>
        <translation>Module einbinden:</translation>
    </message>
    <message>
        <location filename="../../CxFreeze/CxfreezeConfigDialog.ui" line="343"/>
        <source>Enter a comma separated list of modules to include</source>
        <translation>Gib eine durch Komma getrennte Liste von einzubindenden Modulen ein</translation>
    </message>
    <message>
        <location filename="../../CxFreeze/CxfreezeConfigDialog.ui" line="350"/>
        <source>Exclude modules:</source>
        <translation>Module ausschließen:</translation>
    </message>
    <message>
        <location filename="../../CxFreeze/CxfreezeConfigDialog.ui" line="357"/>
        <source>Enter a comma separated list of modules to exclude</source>
        <translation>Gib eine durch Komma getrennte Liste von auszuschließenden Modulen ein</translation>
    </message>
    <message>
        <location filename="../../CxFreeze/CxfreezeConfigDialog.ui" line="378"/>
        <source>Press to select the external list file via a file selection dialog</source>
        <translation>Drücken, um die externe Listendatei mit einem Dateiauswahldialog auszuwählen</translation>
    </message>
    <message>
        <location filename="../../CxFreeze/CxfreezeConfigDialog.ui" line="364"/>
        <source>Enter the name of a file in which to place the list of included modules</source>
        <translation>Gib den Namen einer Datei ein, in die die Liste der eingebundenen Module geschrieben wird</translation>
    </message>
    <message>
        <location filename="../../CxFreeze/CxfreezeConfigDialog.ui" line="371"/>
        <source>External list file:</source>
        <translation>Externe Listendatei:</translation>
    </message>
    <message>
        <location filename="../../CxFreeze/CxfreezeConfigDialog.ui" line="53"/>
        <source>Application icon:</source>
        <translation>Anwendungs Icon:</translation>
    </message>
    <message>
        <location filename="../../CxFreeze/CxfreezeConfigDialog.ui" line="258"/>
        <source>Enter the name of the application icon.</source>
        <translation>Gib den Namen des Anwendungs-Icons an.</translation>
    </message>
    <message>
        <location filename="../../CxFreeze/CxfreezeConfigDialog.ui" line="91"/>
        <source>Select to compress the byte code in zip files</source>
        <translation>Auswählen, um den Bytecode in zip-Dateien zu komprimieren</translation>
    </message>
    <message>
        <location filename="../../CxFreeze/CxfreezeConfigDialog.ui" line="94"/>
        <source>Compress Byte Code</source>
        <translation>Bytecode komprimieren</translation>
    </message>
    <message>
        <location filename="../../CxFreeze/CxfreezeConfigDialog.ui" line="251"/>
        <source>cx_Freeze executable:</source>
        <translation>cx_Freeze Startdatei:</translation>
    </message>
    <message>
        <location filename="../../CxFreeze/CxfreezeConfigDialog.py" line="342"/>
        <source>Icons</source>
        <translation>Icons</translation>
    </message>
    <message>
        <location filename="../../CxFreeze/CxfreezeConfigDialog.py" line="343"/>
        <source>All files</source>
        <translation>Alle Dateien</translation>
    </message>
    <message>
        <location filename="../../CxFreeze/CxfreezeConfigDialog.py" line="351"/>
        <source>Select the application icon</source>
        <translation>Wähle das Icon für die Anwendung</translation>
    </message>
    <message>
        <location filename="../../CxFreeze/CxfreezeConfigDialog.ui" line="244"/>
        <source>Select the cx_freeze executable</source>
        <translation>Wähle die cx_Freeze Startdatei</translation>
    </message>
    <message>
        <location filename="../../CxFreeze/CxfreezeConfigDialog.ui" line="402"/>
        <source>Additional &amp;files</source>
        <translation>Zusätzliche &amp;Dateien</translation>
    </message>
    <message>
        <location filename="../../CxFreeze/CxfreezeConfigDialog.ui" line="415"/>
        <source>List of files and directories which are copied into the distribution directory
See &apos;What&apos;s this&apos;</source>
        <translation>Liste der Dateien und Verzeichnisse, welche in den Distributions-Ordner kopiert werden
Siehe auch &apos;Hilfe&apos;</translation>
    </message>
    <message>
        <location filename="../../CxFreeze/CxfreezeConfigDialog.ui" line="419"/>
        <source>&lt;html&gt;&lt;head/&gt;&lt;body&gt;&lt;p&gt;&lt;span style=&quot; font-weight:600;&quot;&gt;Additional files list&lt;/span&gt;&lt;/p&gt;&lt;p&gt;Here you can add files and folders which will not frozen by cx_Freeze, but maybe relevant to your application. This could be, e.g., some UI files or a dirctory with your translation files.&lt;/p&gt;&lt;p&gt;Easily add them to the list and they get copied after the freeze.&lt;/p&gt;&lt;p&gt;Remarks: &lt;/p&gt;&lt;p&gt;- Every file or folder will be copied relativ to the destination folder even if it&apos;s outside the sourcetree.&lt;/p&gt;&lt;p&gt;- Files and folders don&apos;t have to be added to the Eric project first.&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</source>
        <translation>&lt;html&gt;&lt;head/&gt;&lt;body&gt;&lt;p&gt;&lt;span style=&quot; font-weight:600;&quot;&gt;Liste zusätzlicher Dateien&lt;/span&gt;&lt;/p&gt;&lt;p&gt;Dateien, welche für die Applikation relevant sind, aber nicht von cx_Freeze eingebunden werden, können hier hinzugefügt werden. Dies können z.B. Dateien für das UI oder ein Ordner  mit den Übersetzungen sein.&lt;/p&gt;&lt;p&gt;Die hinzugefügten Dateien und Ordner werden nach dem Erstellen der Applikation dazukopiert.&lt;/p&gt;&lt;p&gt;Hinweise: &lt;/p&gt;&lt;p&gt;- Jede Datei bzw. jeder Ordner wird relativ zu dem Zielordner kopiert, auch wenn die Quelle außerhalb des Quellcodeverzeichnisses liegt.&lt;/p&gt;&lt;p&gt;- Dateien bzw. Verzeichnisse brauchen nicht dem Eric Projekt hinzugefügt worden sein.&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</translation>
    </message>
    <message>
        <location filename="../../CxFreeze/CxfreezeConfigDialog.ui" line="434"/>
        <source>Press to delete the selected entry from the list</source>
        <translation>Drücken, um den ausgewählten Eintrag aus der Liste zu löschen</translation>
    </message>
    <message>
        <location filename="../../CxFreeze/CxfreezeConfigDialog.ui" line="437"/>
        <source>Delete</source>
        <translation>Löschen</translation>
    </message>
    <message>
        <location filename="../../CxFreeze/CxfreezeConfigDialog.ui" line="447"/>
        <source>Press to add the entered file or directory to the list</source>
        <translation>Drücken, um die eingegebene(n) Datei(en)/ Ordner der Liste hinzuzufügen</translation>
    </message>
    <message>
        <location filename="../../CxFreeze/CxfreezeConfigDialog.ui" line="450"/>
        <source>Add</source>
        <translation>Hinzufügen</translation>
    </message>
    <message>
        <location filename="../../CxFreeze/CxfreezeConfigDialog.ui" line="457"/>
        <source>Enter a file or directory to be added.
Wildcards are allowed, e.g. *.ui</source>
        <translation>Eine Datei oder ein Verzeichnis eingeben, welches hinzugefügt werden soll.
Platzhalter sind erlaubt, wie z.B. *.ui</translation>
    </message>
    <message>
        <location filename="../../CxFreeze/CxfreezeConfigDialog.py" line="523"/>
        <source>Select files and folders</source>
        <translation>Wähle Dateien und Ordner</translation>
    </message>
    <message>
        <location filename="../../CxFreeze/CxfreezeConfigDialog.ui" line="465"/>
        <source>Press to select a file or directory via a selection dialog</source>
        <translation>Drücken, um Dateinen und Ordner über einen Dialog auszuwählen</translation>
    </message>
    <message>
        <location filename="../../CxFreeze/CxfreezeConfigDialog.ui" line="408"/>
        <source>Add depending files or folders to copy into the distribution folder:</source>
        <translation>Zusätzliche Dateien oder Ordner, welche in den Distributions-Ordner kopiert werden, hinzufügen:</translation>
    </message>
</context>
<context>
    <name>CxfreezeExecDialog</name>
    <message>
        <location filename="../../CxFreeze/CxfreezeExecDialog.ui" line="14"/>
        <source>Cxfreeze</source>
        <translation>Cxfreeze</translation>
    </message>
    <message>
        <location filename="../../CxFreeze/CxfreezeExecDialog.ui" line="41"/>
        <source>&lt;b&gt;Packager Execution&lt;/b&gt;
&lt;p&gt;This shows the output of the packager command.&lt;/p&gt;</source>
        <translation>&lt;b&gt;Packetierer Ausführung&lt;/b&gt;
&lt;p&gt;Dies zeigt die Ausgabe des Paketierer Befehls.&lt;/p&gt;</translation>
    </message>
    <message>
        <location filename="../../CxFreeze/CxfreezeExecDialog.ui" line="70"/>
        <source>&lt;b&gt;Packager Execution&lt;/b&gt;
&lt;p&gt;This shows the errors of the packager command.&lt;/p&gt;</source>
        <translation>&lt;b&gt;Packetierer Ausführung&lt;/b&gt;
&lt;p&gt;Dies zeigt die Fehler des Paketierer Befehls.&lt;/p&gt;</translation>
    </message>
    <message>
        <location filename="../../CxFreeze/CxfreezeExecDialog.py" line="85"/>
        <source>{0} - {1}</source>
        <translation>{0} - {1}</translation>
    </message>
    <message>
        <location filename="../../CxFreeze/CxfreezeExecDialog.py" line="93"/>
        <source>Process Generation Error</source>
        <translation>Fehler beim Prozessstart</translation>
    </message>
    <message>
        <location filename="../../CxFreeze/CxfreezeExecDialog.py" line="93"/>
        <source>The process {0} could not be started. Ensure, that it is in the search path.</source>
        <translation>Der Prozess {0} konnte nicht gestartet werden. Stellen Sie sicher, dass er sich im Suchpfad befindet.</translation>
    </message>
    <message>
        <location filename="../../CxFreeze/CxfreezeExecDialog.py" line="146"/>
        <source>
{0} finished.
</source>
        <translation>
{0} ist beendet.
</translation>
    </message>
    <message>
        <location filename="../../CxFreeze/CxfreezeExecDialog.ui" line="29"/>
        <source>Messages</source>
        <translation>Meldungen</translation>
    </message>
    <message>
        <location filename="../../CxFreeze/CxfreezeExecDialog.ui" line="58"/>
        <source>Errors</source>
        <translation>Fehler</translation>
    </message>
    <message>
        <location filename="../../CxFreeze/CxfreezeExecDialog.py" line="132"/>
        <source>
{0} aborted.
</source>
        <translation>
{0} abgebrochen.</translation>
    </message>
</context>
<context>
    <name>copyAdditionalFiles</name>
    <message>
        <location filename="../../CxFreeze/CxfreezeExecDialog.py" line="273"/>
        <source>No such file or directory: &apos;{0}&apos;</source>
        <translation>Datei oder Verzeichnis nicht gefunden: {0}</translation>
    </message>
    <message>
        <location filename="../../CxFreeze/CxfreezeExecDialog.py" line="285"/>
        <source>
Copying {0}: </source>
        <translation>
Kopiere {0}: </translation>
    </message>
    <message>
        <location filename="../../CxFreeze/CxfreezeExecDialog.py" line="303"/>
        <source>ok</source>
        <translation>ok</translation>
    </message>
    <message>
        <location filename="../../CxFreeze/CxfreezeExecDialog.py" line="305"/>
        <source>failed: {0}</source>
        <translation>fehlgeschlagen: {0}</translation>
    </message>
</context>
</TS>
