<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.0" language="es">
<context>
    <name>CxFreezePlugin</name>
    <message>
        <location filename="PluginCxFreeze.py" line="50"/>
        <source>Packagers - cx_freeze</source>
        <translation>Empaquetadores - cx_freeze</translation>
    </message>
    <message>
        <location filename="PluginCxFreeze.py" line="148"/>
        <source>Use cx_Freeze</source>
        <translation type="obsolete">Usar cx_Freeze</translation>
    </message>
    <message>
        <location filename="PluginCxFreeze.py" line="148"/>
        <source>Use cx_&amp;Freeze</source>
        <translation type="obsolete">Usar cx_&amp;Freeze</translation>
    </message>
    <message>
        <location filename="PluginCxFreeze.py" line="151"/>
        <source>Generate a distribution package using cx_Freeze</source>
        <translation type="obsolete">Generar un paquete de distribución utilizando cx_Freeze</translation>
    </message>
    <message>
        <location filename="PluginCxFreeze.py" line="153"/>
        <source>&lt;b&gt;Use cx_Freeze&lt;/b&gt;&lt;p&gt;Generate a distribution package using cx_Freeze. The command is executed in the project path. All files and directories must be given absolute or relative to the project directory.&lt;/p&gt;</source>
        <translation type="obsolete">&lt;b&gt;Usar cx_Freeze&lt;/b&gt;&lt;p&gt;Generar un paquete de distribución utilizando cx_Freeze. El comando se ejecuta en la ruta del proyecto. Todos los archivos y directorios deben ser proporcionados de forma absoluta o relativa al directorio del proyecto.&lt;/p&gt;</translation>
    </message>
    <message>
        <location filename="PluginCxFreeze.py" line="196"/>
        <source>There is no main script defined for the current project.</source>
        <translation>No hay script principal definido para el proyecto actual.</translation>
    </message>
    <message>
        <location filename="PluginCxFreeze.py" line="207"/>
        <source>The cxfreeze executable could not be found.</source>
        <translation>No se ha podido encontrar el ejecutable de cxfreeze.</translation>
    </message>
    <message>
        <location filename="PluginCxFreeze.py" line="207"/>
        <source>cxfreeze</source>
        <translation>cxfreeze</translation>
    </message>
    <message>
        <location filename="PluginCxFreeze.py" line="139"/>
        <source>Use cx_freeze</source>
        <translation>Usar cx_freeze</translation>
    </message>
    <message>
        <location filename="PluginCxFreeze.py" line="139"/>
        <source>Use cx_&amp;freeze</source>
        <translation>Usar cx_&amp;freeze</translation>
    </message>
    <message>
        <location filename="PluginCxFreeze.py" line="142"/>
        <source>Generate a distribution package using cx_freeze</source>
        <translation>Generar un paquete de distribución utilizando cx_freeze</translation>
    </message>
    <message>
        <location filename="PluginCxFreeze.py" line="144"/>
        <source>&lt;b&gt;Use cx_freeze&lt;/b&gt;&lt;p&gt;Generate a distribution package using cx_freeze. The command is executed in the project path. All files and directories must be given absolute or relative to the project directory.&lt;/p&gt;</source>
        <translation>&lt;b&gt;Usar cx_freeze&lt;/b&gt;&lt;p&gt;Generar un paquete de distribución utilizando cx_freeze. El comando se ejecuta en la ruta del proyecto. Todos los archivos y directorios deben ser proporcionados de forma absoluta o relativa al directorio del proyecto.&lt;/p&gt;</translation>
    </message>
</context>
<context>
    <name>CxfreezeConfigDialog</name>
    <message>
        <location filename="CxFreeze/CxfreezeConfigDialog.ui" line="14"/>
        <source>Cxfreeze Configuration</source>
        <translation>Configuración de Cxfreeze</translation>
    </message>
    <message>
        <location filename="CxFreeze/CxfreezeConfigDialog.ui" line="17"/>
        <source>&lt;b&gt;Cxfreeze Configuration&lt;/b&gt;
&lt;p&gt;This dialog is used to configure the cxfreeze (FreezePython) process in order to create a distribution package for the project.&lt;/p&gt;
&lt;p&gt;All files and directories must be given absolute or relative to the project directory.&lt;/p&gt;</source>
        <translation>&lt;b&gt;Configuración de Cxfreeze&lt;/b&gt;
&lt;p&gt;Este diálogo se utiliza para configurar el proceso cxfreeze (FreezePython) para crear paquetes de distribución para el proyecto.&lt;/p&gt;
&lt;p&gt;Todos los archivos y directorios deben ser proporcionados de forma absoluta o relativa al directorio del proyecto.&lt;/p&gt;</translation>
    </message>
    <message>
        <location filename="CxFreeze/CxfreezeConfigDialog.ui" line="38"/>
        <source>&amp;General</source>
        <translation>&amp;General</translation>
    </message>
    <message>
        <location filename="CxFreeze/CxfreezeConfigDialog.ui" line="188"/>
        <source>Select to optimize generated bytecode</source>
        <translation>Seleccionar para optimizar el bytecode generado</translation>
    </message>
    <message>
        <location filename="CxFreeze/CxfreezeConfigDialog.ui" line="191"/>
        <source>Optimize bytecode</source>
        <translation>Optimizar bytecode</translation>
    </message>
    <message>
        <location filename="CxFreeze/CxfreezeConfigDialog.ui" line="203"/>
        <source>Don&apos;t optimize</source>
        <translation>No optimizar</translation>
    </message>
    <message>
        <location filename="CxFreeze/CxfreezeConfigDialog.ui" line="210"/>
        <source>Select to optimize the generated bytecode</source>
        <translation>Seleccionar para optimizar el bytecode generado</translation>
    </message>
    <message>
        <location filename="CxFreeze/CxfreezeConfigDialog.ui" line="213"/>
        <source>Optimize</source>
        <translation>Optimizar</translation>
    </message>
    <message>
        <location filename="CxFreeze/CxfreezeConfigDialog.ui" line="220"/>
        <source>Select to optimize the generated bytecode and remove doc strings</source>
        <translation>Seleccionar para optimizar el bytecode generado y eliminar cadenas de documentación</translation>
    </message>
    <message>
        <location filename="CxFreeze/CxfreezeConfigDialog.ui" line="223"/>
        <source>Optimize (with docstring removal)</source>
        <translation>Optimizar (con eliminación de cadenas de documentación)</translation>
    </message>
    <message>
        <location filename="CxFreeze/CxfreezeConfigDialog.ui" line="153"/>
        <source>Select to disable copying of dependent files to the target directory</source>
        <translation>Seleccionar para deshabilitar el copiado de archivos dependientes al directorio de destino</translation>
    </message>
    <message>
        <location filename="CxFreeze/CxfreezeConfigDialog.ui" line="156"/>
        <source>Do not copy dependant files</source>
        <translation>No copiar archivos dependientes</translation>
    </message>
    <message>
        <location filename="CxFreeze/CxfreezeConfigDialog.ui" line="44"/>
        <source>Target directory:</source>
        <translation>Directorio de destino:</translation>
    </message>
    <message>
        <location filename="CxFreeze/CxfreezeConfigDialog.ui" line="51"/>
        <source>Enter the name of the target directory</source>
        <translation>Introduzca el nombre del directorio de destino</translation>
    </message>
    <message>
        <location filename="CxFreeze/CxfreezeConfigDialog.ui" line="54"/>
        <source>&lt;p&gt;Enter the name of the directory in which to place the target file and any dependant files.&lt;/p&gt;</source>
        <translation>&lt;p&gt;Introduzca el nombre del directorio en el cual se ubicará el archivo de destino y todos los archivos dependientes.&lt;/p&gt;</translation>
    </message>
    <message>
        <location filename="CxFreeze/CxfreezeConfigDialog.ui" line="75"/>
        <source>Enter the name of the file to create</source>
        <translation>Introduzca el nombre del archivo a crear</translation>
    </message>
    <message>
        <location filename="CxFreeze/CxfreezeConfigDialog.ui" line="78"/>
        <source>&lt;p&gt;Enter the name of the file to create instead of the base name of the script and the extension of the base binary.&lt;/p&gt;</source>
        <translation>&lt;p&gt;Introduzca el nombre del archivo a crear en lugar del nombre base del script y la extensión del binario base.&lt;/p&gt;</translation>
    </message>
    <message>
        <location filename="CxFreeze/CxfreezeConfigDialog.ui" line="68"/>
        <source>Target name:</source>
        <translation>Nombre de destino:</translation>
    </message>
    <message>
        <location filename="CxFreeze/CxfreezeConfigDialog.ui" line="348"/>
        <source>...</source>
        <translation>...</translation>
    </message>
    <message>
        <location filename="CxFreeze/CxfreezeConfigDialog.ui" line="118"/>
        <source>Enter name of script which will be executed upon startup</source>
        <translation>Introduzca el nombre del script que se ejecutará al iniciar</translation>
    </message>
    <message>
        <location filename="CxFreeze/CxfreezeConfigDialog.ui" line="92"/>
        <source>Enter the name of a file on which to base the target file</source>
        <translation>Introduzca el nombre del archivo en el que basar el archivo de destino</translation>
    </message>
    <message>
        <location filename="CxFreeze/CxfreezeConfigDialog.ui" line="111"/>
        <source>Init script:</source>
        <translation>Script de inicio:</translation>
    </message>
    <message>
        <location filename="CxFreeze/CxfreezeConfigDialog.ui" line="85"/>
        <source>Base name:</source>
        <translation>Nombre base:</translation>
    </message>
    <message>
        <location filename="CxFreeze/CxfreezeConfigDialog.ui" line="234"/>
        <source>&amp;Advanced</source>
        <translation>&amp;Avanzado</translation>
    </message>
    <message>
        <location filename="CxFreeze/Ui_CxfreezeConfigDialog.py" line="208"/>
        <source>Shared library name:</source>
        <translation type="obsolete">Nombre de la biblioteca compartida:</translation>
    </message>
    <message>
        <location filename="CxFreeze/Ui_CxfreezeConfigDialog.py" line="209"/>
        <source>Enter the name of the shared library implementing the Python runtime</source>
        <translation type="obsolete">Introduzca el nombre de la biblioteca compartida implementando el runtime de Python</translation>
    </message>
    <message>
        <location filename="CxFreeze/CxfreezeConfigDialog.ui" line="252"/>
        <source>Default path</source>
        <translation>Ruta por defecto</translation>
    </message>
    <message>
        <location filename="CxFreeze/CxfreezeConfigDialog.ui" line="259"/>
        <source>Enter directories to initialize sys.path</source>
        <translation>Introduzca los directorios para inicializar sys.path</translation>
    </message>
    <message>
        <location filename="CxFreeze/CxfreezeConfigDialog.ui" line="262"/>
        <source>&lt;p&gt;Enter a list of paths separated by the standard path separator, which will be used to initialize sys.path prior to running the module finder.&lt;/p&gt;</source>
        <translation>&lt;p&gt;Introduzca una lista de rutas separadas por el separador estándar de rutas. Esta ruta se utilizará para inicializar sys.path antes de ejecutar el buscador de módulos.&lt;/p&gt;</translation>
    </message>
    <message>
        <location filename="CxFreeze/CxfreezeConfigDialog.ui" line="269"/>
        <source>Enter directories to modify sys.path</source>
        <translation>Introduzca directorios para modificar sys.path</translation>
    </message>
    <message>
        <location filename="CxFreeze/CxfreezeConfigDialog.ui" line="272"/>
        <source>&lt;p&gt;Enter a list of paths separated by the standard path separator, which will be used to modify sys.path prior to running the module finder.&lt;/p&gt;</source>
        <translation>&lt;p&gt;Introduzca una lista de rutas separadas por el separador estándar de rutas. Esta ruta se utilizará para modificar sys.path antes de ejecutar el buscador de módulos.&lt;/p&gt;</translation>
    </message>
    <message>
        <location filename="CxFreeze/CxfreezeConfigDialog.ui" line="279"/>
        <source>Include path</source>
        <translation>Ruta de include</translation>
    </message>
    <message>
        <location filename="CxFreeze/CxfreezeConfigDialog.ui" line="286"/>
        <source>Replace paths:</source>
        <translation>Rutas de reemplazamiento:</translation>
    </message>
    <message>
        <location filename="CxFreeze/CxfreezeConfigDialog.ui" line="293"/>
        <source>Enter replacement directives</source>
        <translation>Introduzca directivas de reemplazamiento</translation>
    </message>
    <message>
        <location filename="CxFreeze/CxfreezeConfigDialog.ui" line="296"/>
        <source>&lt;p&gt;Enter replacement directives used to replace all the paths in modules found. Please see cx_Freeze docu for details.&lt;/p&gt;</source>
        <translation>&lt;p&gt;Introduzca las directivas de reemplazamiento utilizadas para sustituir todas las rutas en los módulos encontrados. Por favor vea la documentación de cx_Freeze para detalles.&lt;/p&gt;</translation>
    </message>
    <message>
        <location filename="CxFreeze/CxfreezeConfigDialog.ui" line="303"/>
        <source>Include modules:</source>
        <translation>Incluir módulos:</translation>
    </message>
    <message>
        <location filename="CxFreeze/CxfreezeConfigDialog.ui" line="310"/>
        <source>Enter a comma separated list of modules to include</source>
        <translation>Introduzca una lista de módulos a incluir separados por comas</translation>
    </message>
    <message>
        <location filename="CxFreeze/CxfreezeConfigDialog.ui" line="317"/>
        <source>Exclude modules:</source>
        <translation>Excluir módulos:</translation>
    </message>
    <message>
        <location filename="CxFreeze/CxfreezeConfigDialog.ui" line="324"/>
        <source>Enter a comma separated list of modules to exclude</source>
        <translation>Introduzca una lista de módulos a excluir separados por comas</translation>
    </message>
    <message>
        <location filename="CxFreeze/Ui_CxfreezeConfigDialog.py" line="223"/>
        <source>Press to select the Python shared library via a file selection dialog</source>
        <translation type="obsolete">Pulse para seleccionar la biblioteca compartida de Python a través de un diálogo de selección de archivo</translation>
    </message>
    <message>
        <location filename="CxFreeze/CxfreezeConfigDialog.ui" line="345"/>
        <source>Press to select the external list file via a file selection dialog</source>
        <translation>Pulse para seleccionar el archivo de lista externo a traves de un diálogo de selección de archivo</translation>
    </message>
    <message>
        <location filename="CxFreeze/CxfreezeConfigDialog.ui" line="331"/>
        <source>Enter the name of a file in which to place the list of included modules</source>
        <translation>Introduzca el nombre de un archivo en el que ubicar la lista de módulos incluidos</translation>
    </message>
    <message>
        <location filename="CxFreeze/CxfreezeConfigDialog.ui" line="338"/>
        <source>External list file:</source>
        <translation>Archivo de lista externo:</translation>
    </message>
    <message>
        <location filename="CxFreeze/CxfreezeConfigDialog.py" line="230"/>
        <source>Select target directory</source>
        <translation>Seleccionar directorio de destino</translation>
    </message>
    <message>
        <location filename="CxFreeze/CxfreezeConfigDialog.py" line="243"/>
        <source>Select Python shared library</source>
        <translation type="obsolete">Seleccionar biblioteca compartida de Python</translation>
    </message>
    <message>
        <location filename="CxFreeze/CxfreezeConfigDialog.py" line="210"/>
        <source>Select external list file</source>
        <translation>Seleccionar archivo de lista externo</translation>
    </message>
    <message>
        <location filename="CxFreeze/CxfreezeConfigDialog.ui" line="137"/>
        <source>Application icon:</source>
        <translation>Icono de la aplicación:</translation>
    </message>
    <message>
        <location filename="CxFreeze/CxfreezeConfigDialog.ui" line="144"/>
        <source>Enter the name of the application icon.</source>
        <translation>Introduzca el nombre del icono de la aplicación.</translation>
    </message>
    <message>
        <location filename="CxFreeze/CxfreezeConfigDialog.ui" line="163"/>
        <source>Select to compress the byte code in zip files</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="CxFreeze/CxfreezeConfigDialog.ui" line="166"/>
        <source>Compress Byte Code</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>CxfreezeExecDialog</name>
    <message>
        <location filename="CxFreeze/CxfreezeExecDialog.ui" line="14"/>
        <source>Cxfreeze</source>
        <translation>Cxfreeze</translation>
    </message>
    <message>
        <location filename="CxFreeze/CxfreezeExecDialog.ui" line="41"/>
        <source>&lt;b&gt;Packager Execution&lt;/b&gt;
&lt;p&gt;This shows the output of the packager command.&lt;/p&gt;</source>
        <translation>&lt;b&gt;Ejecución del empaquetador&lt;/b&gt;
&lt;p&gt;Muestra la salida del comando del empaquetador.&lt;/p&gt;</translation>
    </message>
    <message>
        <location filename="CxFreeze/CxfreezeExecDialog.ui" line="70"/>
        <source>&lt;b&gt;Packager Execution&lt;/b&gt;
&lt;p&gt;This shows the errors of the packager command.&lt;/p&gt;</source>
        <translation>&lt;b&gt;Ejecución del empaquetador&lt;/b&gt;
&lt;p&gt;Muestra los errores del comando del empaquetador.&lt;/p&gt;</translation>
    </message>
    <message>
        <location filename="CxFreeze/CxfreezeExecDialog.py" line="72"/>
        <source>{0} - {1}</source>
        <translation>{0} - {1}</translation>
    </message>
    <message>
        <location filename="CxFreeze/CxfreezeExecDialog.py" line="79"/>
        <source>Process Generation Error</source>
        <translation>Error de Generación de Proceso</translation>
    </message>
    <message>
        <location filename="CxFreeze/CxfreezeExecDialog.py" line="79"/>
        <source>The process {0} could not be started. Ensure, that it is in the search path.</source>
        <translation>El proceso {0} no pudo ser ejecutado. Asegúrese de que esta en la ruta de búsqueda.</translation>
    </message>
    <message>
        <location filename="CxFreeze/CxfreezeExecDialog.py" line="118"/>
        <source>
{0} finished.
</source>
        <translation>{0} ha terminado.</translation>
    </message>
    <message>
        <location filename="CxFreeze/CxfreezeExecDialog.ui" line="29"/>
        <source>Messages</source>
        <translation>Mensajes</translation>
    </message>
    <message>
        <location filename="CxFreeze/CxfreezeExecDialog.ui" line="58"/>
        <source>Errors</source>
        <translation>Errores</translation>
    </message>
</context>
</TS>
