<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS><TS version="2.0" language="ru" sourcelanguage="">
<context>
    <name>CxFreezePlugin</name>
    <message>
        <location filename="PluginCxFreeze.py" line="57"/>
        <source>Packagers - cx_freeze</source>
        <translation>Пакетировщики — cx_freeze</translation>
    </message>
    <message>
        <location filename="PluginCxFreeze.py" line="327"/>
        <source>There is no main script defined for the current project.</source>
        <translation>В текущем проекте не выбран главный сценарий.</translation>
    </message>
    <message>
        <location filename="PluginCxFreeze.py" line="337"/>
        <source>The cxfreeze executable could not be found.</source>
        <translation>cxfreeze не найден.</translation>
    </message>
    <message>
        <location filename="PluginCxFreeze.py" line="337"/>
        <source>cxfreeze</source>
        <translation>cxfreeze</translation>
    </message>
    <message>
        <location filename="PluginCxFreeze.py" line="255"/>
        <source>Use cx_freeze</source>
        <translation>Использовать cx_freeze</translation>
    </message>
    <message>
        <location filename="PluginCxFreeze.py" line="255"/>
        <source>Use cx_&amp;freeze</source>
        <translation>Использовать cx_&amp;freeze</translation>
    </message>
    <message>
        <location filename="PluginCxFreeze.py" line="258"/>
        <source>Generate a distribution package using cx_freeze</source>
        <translation>Создать дистрибутивный пакет с помощью cx_freeze</translation>
    </message>
    <message>
        <location filename="PluginCxFreeze.py" line="260"/>
        <source>&lt;b&gt;Use cx_freeze&lt;/b&gt;&lt;p&gt;Generate a distribution package using cx_freeze. The command is executed in the project path. All files and directories must be given absolute or relative to the project directory.&lt;/p&gt;</source>
        <translation>&lt;b&gt;Использовать cx_freeze&lt;/b&gt;
&lt;p&gt;Создать дистрибутивный пакет с помощью cx_freeze. Команда исполняется в пути проекта. Имена всех файлов и каталогоа должны быть абсолютными или относительными к каталогу проекта.&lt;/p&gt;</translation>
    </message>
    <message>
        <location filename="PluginCxFreeze.py" line="202"/>
        <source>Your version of Eric5 is not supported.
At least version 5.1.0 of Eric5 is needed.</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>CxfreezeConfigDialog</name>
    <message>
        <location filename="CxFreeze/CxfreezeConfigDialog.py" line="259"/>
        <source>Select target directory</source>
        <translation>Выберите каталог назначения</translation>
    </message>
    <message>
        <location filename="CxFreeze/CxfreezeConfigDialog.py" line="210"/>
        <source>Select external list file</source>
        <translation>Выберите файл со списком внешних файлов</translation>
    </message>
    <message>
        <location filename="CxFreeze/CxfreezeConfigDialog.ui" line="14"/>
        <source>Cxfreeze Configuration</source>
        <translation>Конфигурация Cxfreeze</translation>
    </message>
    <message>
        <location filename="CxFreeze/CxfreezeConfigDialog.ui" line="17"/>
        <source>&lt;b&gt;Cxfreeze Configuration&lt;/b&gt;
&lt;p&gt;This dialog is used to configure the cxfreeze (FreezePython) process in order to create a distribution package for the project.&lt;/p&gt;
&lt;p&gt;All files and directories must be given absolute or relative to the project directory.&lt;/p&gt;</source>
        <translation>&lt;b&gt;Конфигурация Cxfreeze&lt;/b&gt;
&lt;p&gt;Этот диалог используется для конфигурирования процесса cxfreeze (FreezeOython), чтобы создать дистрибутивный пакет проекта.&lt;/p&gt;
&lt;p&gt;Пути для всех файлов и каталогов должны быть абсолютными или относительными к каталогу проекта.&lt;/p&gt;</translation>
    </message>
    <message>
        <location filename="CxFreeze/CxfreezeConfigDialog.ui" line="38"/>
        <source>&amp;General</source>
        <translation>&amp;Общее</translation>
    </message>
    <message>
        <location filename="CxFreeze/CxfreezeConfigDialog.ui" line="181"/>
        <source>Select to optimize generated bytecode</source>
        <translation>Оптимизировать генерируемый байт-код</translation>
    </message>
    <message>
        <location filename="CxFreeze/CxfreezeConfigDialog.ui" line="184"/>
        <source>Optimize bytecode</source>
        <translation>Оптимизировать байт-код</translation>
    </message>
    <message>
        <location filename="CxFreeze/CxfreezeConfigDialog.ui" line="196"/>
        <source>Don&apos;t optimize</source>
        <translation>Не оптимизировать</translation>
    </message>
    <message>
        <location filename="CxFreeze/CxfreezeConfigDialog.ui" line="203"/>
        <source>Select to optimize the generated bytecode</source>
        <translation>Оптимизировать генерируемый байт-код</translation>
    </message>
    <message>
        <location filename="CxFreeze/CxfreezeConfigDialog.ui" line="206"/>
        <source>Optimize</source>
        <translation>Оптимизировать</translation>
    </message>
    <message>
        <location filename="CxFreeze/CxfreezeConfigDialog.ui" line="213"/>
        <source>Select to optimize the generated bytecode and remove doc strings</source>
        <translation>Оптимизировать генерируемый байт-код и удалить строки документации</translation>
    </message>
    <message>
        <location filename="CxFreeze/CxfreezeConfigDialog.ui" line="216"/>
        <source>Optimize (with docstring removal)</source>
        <translation>Оптимизировать (с удалением строк документации)</translation>
    </message>
    <message>
        <location filename="CxFreeze/CxfreezeConfigDialog.ui" line="72"/>
        <source>Select to disable copying of dependent files to the target directory</source>
        <translation>Запретить копирование зависимых файлов в целевой каталог</translation>
    </message>
    <message>
        <location filename="CxFreeze/CxfreezeConfigDialog.ui" line="75"/>
        <source>Do not copy dependant files</source>
        <translation>Не копировать зависимости</translation>
    </message>
    <message>
        <location filename="CxFreeze/CxfreezeConfigDialog.ui" line="174"/>
        <source>Target directory:</source>
        <translation>Каталог назначения:</translation>
    </message>
    <message>
        <location filename="CxFreeze/CxfreezeConfigDialog.ui" line="145"/>
        <source>Enter the name of the target directory</source>
        <translation>Задайте имя целевого каталога</translation>
    </message>
    <message>
        <location filename="CxFreeze/CxfreezeConfigDialog.ui" line="148"/>
        <source>&lt;p&gt;Enter the name of the directory in which to place the target file and any dependant files.&lt;/p&gt;</source>
        <translation>&lt;p&gt;Задайте имя каталога, в который поместить целевой файл и любые его зависимости.&lt;/p&gt;</translation>
    </message>
    <message>
        <location filename="CxFreeze/CxfreezeConfigDialog.ui" line="121"/>
        <source>Enter the name of the file to create</source>
        <translation>Задайте имя файла, который надо создать</translation>
    </message>
    <message>
        <location filename="CxFreeze/CxfreezeConfigDialog.ui" line="124"/>
        <source>&lt;p&gt;Enter the name of the file to create instead of the base name of the script and the extension of the base binary.&lt;/p&gt;</source>
        <translation>&lt;p&gt;Задайте имя файла, который надо создать, вместо указания базового имени сценария и расширения базового двоичного файла.&lt;/p&gt;</translation>
    </message>
    <message>
        <location filename="CxFreeze/CxfreezeConfigDialog.ui" line="114"/>
        <source>Target name:</source>
        <translation>Имя цели:</translation>
    </message>
    <message>
        <location filename="CxFreeze/CxfreezeConfigDialog.ui" line="363"/>
        <source>...</source>
        <translation>...</translation>
    </message>
    <message>
        <location filename="CxFreeze/CxfreezeConfigDialog.ui" line="51"/>
        <source>Enter name of script which will be executed upon startup</source>
        <translation>Задайте имя сценария, который будет выполняться при старте</translation>
    </message>
    <message>
        <location filename="CxFreeze/CxfreezeConfigDialog.ui" line="155"/>
        <source>Enter the name of a file on which to base the target file</source>
        <translation>Задайте имя файла, на котором будет базироваться целевой файл</translation>
    </message>
    <message>
        <location filename="CxFreeze/CxfreezeConfigDialog.ui" line="107"/>
        <source>Init script:</source>
        <translation>Инициализирующий сценарий:</translation>
    </message>
    <message>
        <location filename="CxFreeze/CxfreezeConfigDialog.ui" line="131"/>
        <source>Base name:</source>
        <translation>Базовое имя:</translation>
    </message>
    <message>
        <location filename="CxFreeze/CxfreezeConfigDialog.ui" line="255"/>
        <source>&amp;Advanced</source>
        <translation>&amp;Дополнительно</translation>
    </message>
    <message>
        <location filename="CxFreeze/CxfreezeConfigDialog.ui" line="267"/>
        <source>Default path</source>
        <translation>Путь по-умолчанию</translation>
    </message>
    <message>
        <location filename="CxFreeze/CxfreezeConfigDialog.ui" line="274"/>
        <source>Enter directories to initialize sys.path</source>
        <translation>Задайте каталоги для инициализации sys.path</translation>
    </message>
    <message>
        <location filename="CxFreeze/CxfreezeConfigDialog.ui" line="277"/>
        <source>&lt;p&gt;Enter a list of paths separated by the standard path separator, which will be used to initialize sys.path prior to running the module finder.&lt;/p&gt;</source>
        <translation>&lt;p&gt;Задайте список путей, которые будут использованы для инициализации sys.path перед тем, как запустится поиск модулей. 
Они должны быть рзделены символом стандартного разделителя элементов PATH&lt;/p&gt;</translation>
    </message>
    <message>
        <location filename="CxFreeze/CxfreezeConfigDialog.ui" line="284"/>
        <source>Enter directories to modify sys.path</source>
        <translation>Задайте каталоги для изменения sys.path</translation>
    </message>
    <message>
        <location filename="CxFreeze/CxfreezeConfigDialog.ui" line="287"/>
        <source>&lt;p&gt;Enter a list of paths separated by the standard path separator, which will be used to modify sys.path prior to running the module finder.&lt;/p&gt;</source>
        <translation>&lt;p&gt;Задайте список путей, которые будут использованы для изменения sys.path перед тем, как запустится поиск модулей. 
Они должны быть рзделены символом стандартного разделителя элементов PATH&lt;/p&gt;</translation>
    </message>
    <message>
        <location filename="CxFreeze/CxfreezeConfigDialog.ui" line="294"/>
        <source>Include path</source>
        <translation>Включить путь</translation>
    </message>
    <message>
        <location filename="CxFreeze/CxfreezeConfigDialog.ui" line="301"/>
        <source>Replace paths:</source>
        <translation>Заменить пути:</translation>
    </message>
    <message>
        <location filename="CxFreeze/CxfreezeConfigDialog.ui" line="308"/>
        <source>Enter replacement directives</source>
        <translation>Задайте директивы замещения</translation>
    </message>
    <message>
        <location filename="CxFreeze/CxfreezeConfigDialog.ui" line="311"/>
        <source>&lt;p&gt;Enter replacement directives used to replace all the paths in modules found. Please see cx_Freeze docu for details.&lt;/p&gt;</source>
        <translation>&lt;p&gt;Задайте директивы замещения, используемые для замены всех путей, в найденных модулях. Для подробностей, пожалуйста, обратитесь к документации cx_Freeze.&lt;/p&gt;</translation>
    </message>
    <message>
        <location filename="CxFreeze/CxfreezeConfigDialog.ui" line="318"/>
        <source>Include modules:</source>
        <translation>Включить модули:</translation>
    </message>
    <message>
        <location filename="CxFreeze/CxfreezeConfigDialog.ui" line="325"/>
        <source>Enter a comma separated list of modules to include</source>
        <translation>Задайте список модулей для включения, разделённый запятыми</translation>
    </message>
    <message>
        <location filename="CxFreeze/CxfreezeConfigDialog.ui" line="332"/>
        <source>Exclude modules:</source>
        <translation>Не включать модули:</translation>
    </message>
    <message>
        <location filename="CxFreeze/CxfreezeConfigDialog.ui" line="339"/>
        <source>Enter a comma separated list of modules to exclude</source>
        <translation>Задайте разделённый запятыми список модулей, которые нельзя включать</translation>
    </message>
    <message>
        <location filename="CxFreeze/CxfreezeConfigDialog.ui" line="360"/>
        <source>Press to select the external list file via a file selection dialog</source>
        <translation>Выберите внешний файл со списком с помощью файлового диалога</translation>
    </message>
    <message>
        <location filename="CxFreeze/CxfreezeConfigDialog.ui" line="346"/>
        <source>Enter the name of a file in which to place the list of included modules</source>
        <translation>Задайте имя файла, в который поместить список используемых модулей</translation>
    </message>
    <message>
        <location filename="CxFreeze/CxfreezeConfigDialog.ui" line="353"/>
        <source>External list file:</source>
        <translation>Внешний файл со списком:</translation>
    </message>
    <message>
        <location filename="CxFreeze/CxfreezeConfigDialog.ui" line="44"/>
        <source>Application icon:</source>
        <translation>символ прикладной программы:</translation>
    </message>
    <message>
        <location filename="CxFreeze/CxfreezeConfigDialog.ui" line="240"/>
        <source>Enter the name of the application icon.</source>
        <translation>Задайте имя файла символа прикладной программы.</translation>
    </message>
    <message>
        <location filename="CxFreeze/CxfreezeConfigDialog.ui" line="82"/>
        <source>Select to compress the byte code in zip files</source>
        <translation>Сжать объектный код в zip архив</translation>
    </message>
    <message>
        <location filename="CxFreeze/CxfreezeConfigDialog.ui" line="85"/>
        <source>Compress Byte Code</source>
        <translation>Сжать объектный код</translation>
    </message>
    <message>
        <location filename="CxFreeze/CxfreezeConfigDialog.ui" line="226"/>
        <source>Select the cx_freeze executable</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="CxFreeze/CxfreezeConfigDialog.ui" line="233"/>
        <source>cx_Freeze executable:</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="CxFreeze/CxfreezeConfigDialog.py" line="230"/>
        <source>Icons</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="CxFreeze/CxfreezeConfigDialog.py" line="231"/>
        <source>All files</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="CxFreeze/CxfreezeConfigDialog.py" line="239"/>
        <source>Select the application icon</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>CxfreezeExecDialog</name>
    <message>
        <location filename="CxFreeze/CxfreezeExecDialog.ui" line="14"/>
        <source>Cxfreeze</source>
        <translation>Cxfreeze</translation>
    </message>
    <message>
        <location filename="CxFreeze/CxfreezeExecDialog.ui" line="41"/>
        <source>&lt;b&gt;Packager Execution&lt;/b&gt;
&lt;p&gt;This shows the output of the packager command.&lt;/p&gt;</source>
        <translation>&lt;b&gt;Выполнение упаковщика&lt;/b&gt;
&lt;p&gt;Отображает вывод команды упаковщика.&lt;/p&gt;</translation>
    </message>
    <message>
        <location filename="CxFreeze/CxfreezeExecDialog.ui" line="70"/>
        <source>&lt;b&gt;Packager Execution&lt;/b&gt;
&lt;p&gt;This shows the errors of the packager command.&lt;/p&gt;</source>
        <translation>&lt;b&gt;Выполнение упаковщика&lt;/b&gt;
&lt;p&gt;Отображает ошибки команды упаковщика.&lt;/p&gt;</translation>
    </message>
    <message>
        <location filename="CxFreeze/CxfreezeExecDialog.py" line="75"/>
        <source>{0} - {1}</source>
        <translation>{0} - {1}</translation>
    </message>
    <message>
        <location filename="CxFreeze/CxfreezeExecDialog.py" line="83"/>
        <source>Process Generation Error</source>
        <translation>Ошибка процесса генерации</translation>
    </message>
    <message>
        <location filename="CxFreeze/CxfreezeExecDialog.py" line="83"/>
        <source>The process {0} could not be started. Ensure, that it is in the search path.</source>
        <translation>Не могу запустить процесс &apos;{0}&apos;. Убедитесь, что он находится в пути поиска.</translation>
    </message>
    <message>
        <location filename="CxFreeze/CxfreezeExecDialog.py" line="122"/>
        <source>
{0} finished.
</source>
        <translation>{0} завершился.</translation>
    </message>
    <message>
        <location filename="CxFreeze/CxfreezeExecDialog.ui" line="29"/>
        <source>Messages</source>
        <translation>сообщение</translation>
    </message>
    <message>
        <location filename="CxFreeze/CxfreezeExecDialog.ui" line="58"/>
        <source>Errors</source>
        <translation>ошибка</translation>
    </message>
</context>
</TS>
